modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "enable_trial_spawner"
version = "${version}"
displayName = "Enable trial spawner"
authors = "Akxe"
description = '''
Allows trial spawners to spawn mobs even if the doMobSpawning gamerule is set to false, matching vanilla mob spawner logic.
'''
#logoFile = "assets/enable_trial_spawner/icon.png"

[[dependencies.enable_trial_spawner]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enable_trial_spawner]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enable_trial_spawner]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "enable_trial_spawner.mixins.json"
